[build]
builder = "nixpacks"
buildCommand = "cd api && pip install -r requirements.txt && pip install gunicorn"

[deploy]
startCommand = "cd api && gunicorn --bind 0.0.0.0:$PORT app:create_app()"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["python310", "gcc"]

[variables]
FLASK_APP = "app.py"
FLASK_ENV = "production"
HOST = "0.0.0.0"
