[build]
builder = "nixpacks"
buildCommand = """
cd api && 
pip install -r requirements.txt &&
pip install gevent grpcio monkey gunicorn
"""

[deploy]
startCommand = "cd api && gunicorn -k gevent 'app:app' --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["python310", "gcc", "python310Packages.pip"]

[variables]
FLASK_APP = "app.py"
FLASK_ENV = "production"
HOST = "0.0.0.0"
DEPLOY_ENV = "production"
DEBUG = "false"
TESTING = "false"
