[build]
builder = "nixpacks"
buildCommand = "cd api && pip install -r requirements.txt"

[deploy]
startCommand = "cd api && python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["python310", "gcc"]

[variables]
FLASK_APP = "app.py"
FLASK_ENV = "production"
HOST = "0.0.0.0"
PORT = "5001"
DEBUG = "false"
DEPLOY_ENV = "production"
